# DON'T EDIT THE TEMPLATE FILE.
# Instead copy the content of this file to config.yml, set up your settings and it is going to be used
# as a config for this project.

# Bot token from https://discord.com/developers/applications/
bot-token: "0"

# Id of a server which is going to be used for set up
server-id: 0

# PostgreSQL connection string
db-connection-string: "connection string"

# Log severity level
# Options: Verbose, Debug, Info, Warning, Error, Critical
log-severity: "Info"

# Playing a game module
presence:
  enabled: False
  game-name: "PixelPlace 2"

# Giving a role with ID when user sets reactions to a message 
reaction-role:
  enabled: False
  role-id: 0
  message-id: 0
  emote-name: "✅"

# Ranks are changed when user receives a corresponding role
ranks:
  - name: "Rank1" # Name should be unique for each rank
    id: 0 # Discord role id
    priority: 0 # The higher the priority, the higher the role
    image: "ranks/rank1.png" # the path relative to the location of the bot executable
  - name: "Rank2"
    id: 1
    priority: 1
    image: "ranks/rank2.png"

# User's awards are added and removed by using /award and /remove-award slash commands
# Discord slash command auto-complete supports max of 25 entries
awards:
  - id: "Medal1" # Unique name for each award without spaces
    name: "Medal 1" # Medal name which is going to be shows
    importance: 1 # How many points the award gives for the user rating
    image: "assets/medals/medal1.png" # the path relative to the location of the bot executable
    badge: "assets/medals/medal1_badge.png" # going to be used as a smaller version of an image
  - id: "Medal2"
    name: "Medal Something"
    importance: 1
    image: "assets/medals/medal2.png"
    badge: "assets/medals/medal2_badge.png"

# Image generation settings
image-gen:
  # Background image when user receives an award
  award-received-background: "assets/new_award_template.png"
  # Background image in profile
  profile-background: "assets/profile_template.png"
  font:
    path: "assets/minecraft.ttf"
    size: 20
    # Regular, Italic, Bold, BoldItalic
    style: "Regular"
    # Color in HEX
    color:
      primary: "#FFFF00"
      secondary: "#FFFFFF"
  # All objects should be placed within the picture
  profile:
    award-name-cords:
      x: 120
      y: 32
    description-cords:
      x: 120
      y: 64
    award-badge-cords:
      x: 40
      y: 44