# DON'T EDIT THE TEMPLATE FILE.
# Instead copy the content of this file to config.yml, set up your settings and it is going to be used
# as a config for this project.

# Bot token from https://discord.com/developers/applications/
bot-token: "0"

# Id of a server which is going to be used for set up
server-id: 0

# PostgreSQL connection string
db-connection-string: "connection string"

# Log severity level
# Options: Verbose, Debug, Info, Warning, Error, Critical
log-severity: "Info"

# Playing a game module
presence:
  enabled: False
  game-name: "PixelPlace 2"

# Giving a role with ID when user sets reactions to a message 
reaction-role:
  enabled: False
  role-id: 0
  message-id: 0
  emote-name: "✅"